# Generated by Django 3.0.5 on 2020-04-22 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200421_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='Order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thorders', to='accounts.Order'),
        ),
    ]
